### ISSUE TITLE
The plugin has stopped working on 4.1

### ISSUE THREAD

**Issue by sangeeyeah** [catalyst/moodle-local_quiz_summary_option#4] opened 2023-05-29 10:34 UTC
Initially, the plugin was throwing an error when the quiz is saved.

"Coding error detected, it must be fixed by a programmer: The 'name' value must be set in other."

However, with the latest versions of Moodle 4.1x, the plugin has completely stopped working.

Please see if this can be updated for 4.xx versions of moodle. This is a very useful plugin and sanitizes the user experience by getting rid of the quiz_summary page when not required.

**Comment by danmarsden** [comment] 2023-05-29 22:41
Hi @sangeeyeah - unfortunately we can't provide any timeframes but if you would like to fund the development effort required to fix feel free to reach out privately, alternatively if you have internal development capabilities, pull requests are always welcome.

I'm closing this as a duplicate of #3 - thanks!

**Closed as completed by danmarsden** 2023-05-29 22:41 UTC
